config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    post "/signup", to: "users#create"
    delete "/logout", to: "sessions#destroy"
    root "static_pages#home"
    resources :users
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i(new create edit update)
end

app/views/layouts/_footer.html.erb
<footer class="full-row footer">
    <div class="container footer-content">
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <%= link_to image_tag("logo.png", alt: "logo", class: "img-responsive img-logo"), "#" %>
                <p><i>Based in Hanoi, we are creating a system that allows all online users plan, book and administer their own dynamically packaged holidays in Vietnam and Southeast Asia.</i></p>

            </div>
            <div class="col-xs-12 col-sm-3">
                <h3 class="text-uppercase"><b>Contact Info</b></h3>
                <p><span class="fa fa-map-marker text-yellow"></span> Floor, 9, 434 Tran Khat Chan, Hai Ba Trung, Hanoi</p>
                <p><span class="fa fa-phone text-yellow"></span> +84 (0) 98 453 0860</p>
                <p><span class="fa fa-envelope-o text-yellow"></span>  info@tripbricks.com</p>
            </div>
            <div class="col-xs-12 col-sm-3">
                <h3 class="text-uppercase"><b>Discover</b></h3>
                <ul class="list-recent-post">
                    <li>
                        <a href="article.html">About Us</a>
                    </li>
                    <li>
                        <a href="article.html">Terms and conditions</a>
                    </li>
                    <li>
                        <a href="article.html">Privacy policy</a>
                    </li>
                    <li>
                        <a href="article.html">Q&A</a>
                    </li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-3">
                <h3 class="text-uppercase"><b>Connect with us</b></h3>
                <p class="slogan-footer">You got bored on ordinary tours?</br>
                Let’s plan your own dynamically packaged adventures!</p>
                <ul class="list-inline list-connect-us">
                    <li>
                      <%= link_to image_tag("icon-footer/fb.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/dautotuong" %>
                    </li>
                    <li>
                      <%= link_to image_tag("icon-footer/sp.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/dautotuong" %>
                    </li>
                    <li>
                      <%= link_to image_tag("icon-footer/tw.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/dautotuong" %>
                    </li>
                    <li>
                      <%= link_to image_tag("icon-footer/yt.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/dautotuong" %>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<% if current_page?(root_path) || current_page?("/") %>
  <header class="">
<% else %>
  <header class="black-header">
<% end %>
    <!-- <div class="container head-top">
        <div class="pull-right">
        </div>
    </div> -->
    <!-- nav bar -->
    <nav class="navbar">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-3">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to image_tag("logo.png", alt: "logo", class: "img-responsive pull-left img-logo logo-web"), root_path %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar" id="navbar-collapse-3">
                <ul class="nav navbar-nav navbar-left">
                    <li><%= link_to t("Hotels"), "#" %></li>
                    <li><%= link_to t("Destination"), "#" %></li>
                    <li><%= link_to t("Blogs"), "#" %></li>
                    <li><%= link_to t("About"), about_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="li-number">
                        <a href="tel:+84 (0) 98 453 0860"><span class="fa fa-phone text-violet"></span> 098 453 0860</a>
                    </li>
                     <!-- <li>
                        <a class="btn btn-search-top" data-toggle="collapse" href="#nav-collapse3" aria-expanded="false" aria-controls="nav-collapse3"><span class="fa fa-search"></span></a>
                    </li> -->
                    <!--<li class="dropdown select-language">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownLanguage" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            <img src="images/EN-flag.png" alt="" /> <span>EN</span>
                            <span class="fa fa-angle-down"></span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownLanguage">
                            <div class="col-xs-12 col-sm-6 dropdown-language">
                                <h4 class="dropdown-title">Language</h4>
                                <ul>
                                    <li><a href="#"><img src="images/VN-flag.png" alt=""/> Tiếng Việt</a></li>
                                    <li class="selected"><a href="#"><img src="images/EN-flag.png" alt=""/> English</a></li>
                                    <li><a href="#"><img src="images/VN-flag.png" alt=""/> Tiếng Việt</a></li>
                                    <li><a href="#"><img src="images/EN-flag.png" alt=""/> English</a></li>
                                </ul>
                            </div>
                            <div class="col-xs-12 col-sm-6 dropdown-currency">
                                <h4 class="dropdown-title">Currency</h4>
                                <ul>
                                    <li class="selected"><a href="#">VND <span>Việt Nam Đồng</span></a></li>
                                    <li><a href="#">USD <span>Dollar Mỹ</span></a></li>
                                    <li><a href="#">SGD <span>Dollar Singapore</span></a></li>
                                </ul>
                            </div>

                        </div>
                    </li> -->
                    <li class="header-login-register">
                      <% if logged_in? %>
                        <%= link_to @current_user.name, current_user %>
                        <%= link_to t("logout"), logout_path, method: :delete %>
                      <% else %>
                        <%= link_to t("login"), login_path %>
                        <%= link_to t("signup"), signup_path %>
                      <% end %>
                    </li>
                </ul>
                <div class="collapse nav navbar-nav nav-collapse" id="nav-collapse3">
                    <form class="navbar-form navbar-right" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search" />
                        </div>
                        <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                    </form>
                </div>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- /.navbar -->
    <!-- .nav bar -->
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>TripBricks.com</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>